# the name of the plugin
PLUGIN_NAME = viro

# the dissector sources (without any helpers)
DISSECTOR_SRC = packet-viro.c

# corresponding headers
DISSECTOR_INCLUDES =

# Dissector helpers.  They're included in the source files in this
# directory, but they're not dissectors themselves, i.e. they're not
# used to generate "register.c").
DISSECTOR_SUPPORT_SRC =	
